Dev/v3 new UI line numbers
SAP/credential-digger pull request #69
Opened 2020-12-08 10:28 UTC by fabiosangregorio

This PR adds line numbers retrieval during repository scan and stores them in the database (discovery table).

2020-12-08 10:32 UTC, fabiosangregorio commented
I set the default line number to `-1` in the db. Is this ok?

https://github.com/SAP/credential-digger/commit/ce5526004b694e7369022b0efbbea1ca91120c0e#diff-85899f91254d7e4d7e6f50b60c7ea28715768020add3a38d75863e69388a9d0bR41

https://github.com/SAP/credential-digger/commit/ce5526004b694e7369022b0efbbea1ca91120c0e#diff-ae7384d423707e3ab7a59762a57554291e3067e342f7b33adf4211763989c737R21

2020-12-08 10:37 UTC, fabiosangregorio commented
Seeing that hunk headers are in just a few lines (as opposed to addition and deletion lines), I am checking the first two characters before testing for the regex, in chance of improving performance.
https://github.com/SAP/credential-digger/blob/ce5526004b694e7369022b0efbbea1ca91120c0e/credentialdigger/scanners/git_scanner.py#L219-L225

2020-12-11 14:46 UTC, marcorosa requested changes

2020-12-15 16:02 UTC, marcorosa approved these changes

2020-12-15 16:02 UTC, merged