[Feat/https] HTTPS Support
SAP/credential-digger pull request #96
Opened 2021-04-09 15:06 UTC by alaabenfatma

### 🔐 HTTPS SUPPORT

A user can now easily run the web application over HTTPS. It is not mandatory, but it highly recommended.

#### How to
1. We assume you have a signed certificate (certificate.pem) and a private key (key.pem)
 a.  You can run this command to generate a certificate and private key: `openssl req -newkey rsa:2048 -new -nodes -x509 -days 365 -keyout key.pem -out cert.pem`
2. Set up the path of both the certificate and the key in your .env file
```bash
SSL_certificate=/credential-digger-ui/$PATH_to_certificate # i.e /credential-digger-ui/cert.pem
SSL_private_key=/credential-digger-ui/$PATH_to_key # i.e /credential-digger-ui/key.pem
```
3. Start the docker container
```bash
sudo docker-compose up --build
```
If everything works out just fine, you should get this output: `🔐 HTTPS will be used...`

If you leave the SSL variables in the .env file empty, the UI will run on HTTP as usual; resulting in the following output: `🔓 HTTPS will not be used... (HTTP only)`

### Important
Please make sure to make an exception to your self-signed certificate on the browser you are using. Having a warning message the first time you access the web page (i.e 0.0.0.0:5000) is a completely normal behavior because the certificate in use is not signed by a known Certificate Authority.

### Misc
Upon the acceptance of this PR, a wiki page will be set up to explain the process in more details for the users.

2021-04-16 12:06 UTC, marcorosa requested changes
Hi, thanks for the PR.
There are some parts to fix, but overall it's good. 

PS: You can easier your life with a linter

2021-04-16 12:06 UTC, marcorosa commented on .env.sample
> +SSL_certificate=/credential-digger-ui/$PATH_to_certificate # i.e /credential-digger-ui/cert.pem
`/credential-digger-ui/cert.pem` are not actual folders of user's file system. This path is the path that will be created in the docker container, but a standard user doesn't have visibility over this. So, I suggest to leave the path here as the path where to find the certificate (and key) on the local file system, and then they will be put in a suitable folder in the docker container.
In practice, as it happens with the `rules.yaml` file for the rules

2021-04-16 12:06 UTC, marcorosa commented on ui/run.sh
> +if [[ -z "${SSL_certificate}" ]]; then
one or two [[ ? You have used one above (line 5) and two here

2021-04-16 12:06 UTC, marcorosa commented on ui/run.sh
> +if [[ -z "${SSL_private_key}" ]]; then
same comment

2021-04-16 12:06 UTC, marcorosa commented on ui/server.py
> +if __name__ == "__main__":
single quotes for strings in python (in fact you have single quotes at the following line). Double quotes are used for docstrings

2021-04-16 12:06 UTC, marcorosa commented on ui/wsgi.py
> +if __name__ == "__main__":
here again please use single quotes :D

2021-04-19 14:50 UTC, marcorosa requested changes
The file `run.sh` still has mixed cases of [[ and [ in the if statements. Please make them uniform, then I'll merge.

NB for the path to the cert/key: is this path absolute or relative? Or can it be any of them? When you write the wiki page, please specify this :)

2021-04-19 15:17 UTC, alaabenfatma commented
> The file `run.sh` still has mixed cases of [[ and [ in the if statements. Please make them uniform, then I'll merge.
> 
> NB for the path to the cert/key: is this path absolute or relative? Or can it be any of them? When you write the wiki page, please specify this :)

You are right, missed the single brackets, sorry. 
The cert/key path is relative to the wsgi.py file, I will mention this in the wiki page.

2021-04-19 16:01 UTC, marcorosa approved these changes

2021-04-19 16:14 UTC, marcorosa commented
There's a broken test. I will fix the reference with another PR and then will merge also this one

2021-04-20 08:35 UTC, merged

2021-04-20 08:36 UTC, marcorosa commented
NB: verify tests after merge